name: Deploy API

on:
  push:
    branches:
      - main
      - aws-deploy
    # paths:
    #   - "api/**"

defaults:
  run:
    working-directory: ./api

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: "eu-central-1"
      - name: Install AWS Lightsail Client
        run: |
          curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "lightsailctl"
          sudo mv "lightsailctl" "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
      - name: Build and push image to Lightsail
        id: build-image
        run: |
          docker build --build-arg DATABASE_URL="${{ secrets.DATABASE_URL }}"  -t todos_app_api:latest .
          aws lightsail push-container-image --service-name "container-service-1" --label todos_app_api --image ":container-service-1.mystaticwebsite.1"
        env:
          API_HOST: ${{ secrets.API_HOST }}
      - name: Deploy Service
        run: |
          aws lightsail get-container-images --service-name "container-service-1" | jq --raw-output ".containerImages[0].image" > image.txt
          jq --arg image $(cat image.txt) '.containers.app.image = $image' container.template.json > container.json
          aws lightsail create-container-service-deployment --service-name "container-service-1" --cli-input-json file://$(pwd)/container.json

      #  - name: lightsailctl create instance
      #     run: lightsailctl create instance --name "todos-app-api" --region "eu-central-1" --instance-type "t2.micro" --availability-zone "eu-central-1a" --ssh-key-name "todos-app-api" --tags "todos-app-api"
    # aws lightsail create-image --name todos_app_api --instance-name todos_app_api --region eu-central-1
    # aws lightsail publish-image --name todos_app_api --region eu-central-1
